    name: Deploy Eleventy Site to GitHub Pages

    on:
      push:
        branches:
          - main # Se activa cuando haces push a la rama 'main'

    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4 # Descarga tu código

          - name: Set up Node.js
            uses: actions/setup-node@v4 # Configura Node.js
            with:
              node-version: '18' # Puedes ajustar la versión si es necesario
              cache: 'npm' # Habilita caché para npm

          - name: Install dependencies
            run: npm ci # Instala las dependencias desde package-lock.json (más rápido y seguro)

          - name: Build Eleventy site
            run: npm run build # Ejecuta el script de build

          - name: Deploy to YonisEsquivel/cashfreed (gh-pages)
            uses: peaceiris/actions-gh-pages@v3
            with:
              personal_token: ${{ secrets.GH_TOKEN_YONIS }}
              publish_dir: ./_site
              publish_branch: gh-pages # Rama destino para tu cuenta
              user_name: 'github-actions[bot]'
              user_email: 'github-actions[bot]@users.noreply.github.com'
              commit_message: 'Deploy to YonisEsquivel gh-pages [skip ci]'
              # No se especifica 'external_repository' ya que es el mismo repo

          - name: Deploy to cashfreed/cashfreed.github.io (main)
            uses: peaceiris/actions-gh-pages@v3
            with:
              personal_token: ${{ secrets.GH_TOKEN_CASHFREED }}
              publish_dir: ./_site
              publish_branch: main # Rama destino para la cuenta cashfreed
              external_repository: cashfreed/cashfreed.github.io # Repositorio externo
              user_name: 'github-actions[bot]'
              user_email: 'github-actions[bot]@users.noreply.github.com'
              commit_message: 'Deploy to cashfreed main [skip ci]'
              # Añadir '--force' si es necesario para sobrescribir la rama main
              # force_orphan: true # Opcional: si quieres que cada deploy sea limpio
